### ISSUE TITLE
CI: refactor kubecf pipeline: requirements list

### ISSUE THREAD

**Issue by viccuad** [cloudfoundry-incubator/kubecf#1064]
**Is your feature request related to a problem? Please describe.**

Several requirements for CI pipelines pop up here and there, left to be forgotten. These requirements inform a specific design, and this issue tries to collect them for discussion.

**Describe the solution you'd like**

A pipeline with following requirements:

- [ ] Maintain current features (github status, publish, artifacts, prod/experimental jobs,..)
- [ ] Have options to deploy development copies of the pipeline.
- [ ] Have manageable chunks, in topical folders, with matching file extensions for linting correctly (https://github.com/cloudfoundry-incubator/kubecf/issues/443).
   Eg: have shellscripts in .sh files to be linted appropriately.
- [ ] Allow jumping easily between providers: helps external contributors deploy their copy of the pipeline, we may hit quotas, unexpected problems, or need to expand testing to multiple providers.
  Eg: Add a pool system to contain the clusters. These can be created or destroyed just like now (GKE preemptible), with Catapult, or EKCP. Consider managing the creation and deletion out of the testing pipelines, and in a reconciler pipeline that monitors the pool folders and numbers (see https://github.com/cloudfoundry-incubator/kubecf/issues/682).
  - Semver for cluster names is not enough: copies of the pipeline can use the same semver number for the cluster name as the production pipeline, creating conflicts.
- [ ] Cleanup clusters correctly.
  - If it is already running CATS, will closing the PR prevent it from running the cleanup task?
- [ ] Transient artifacts (the ones current in s3.kubecf-ci) that can be used in development copies of the pipeline.
    Eg: Artifacts could be marked with a commit hash and possibly datetime info, to make them unique. This allows for sharing draft buckets used for developing the pipeline.
- [ ] Allow flying several pipelines, one per branch to be tested (`master`, `release-2.2`, `release-2.3`).
     Eg: We may need jobs to be in experimental in old branches, yet they are already in production in new branches or master. This means that we may need to move out of tabs and into deploying 1 pipeline per branch.
  - what happens with github statuses once we have several pipelines? do 2 different pipelines update the status of the same commit?
- [ ] Allow for a cache registry (https://github.com/cloudfoundry-incubator/kubecf/issues/602)
  This would be good to have independently of k8s provider, as it may aid in testing airgapped deployments. But public cloud clusters are ephemeral, so no speed gain happens there. 
- [ ] Allow to trigger only some testsuites per PR, eg, only CATS (https://github.com/cloudfoundry-incubator/kubecf/issues/628#issuecomment-610076082)
- [ ] Trigger Publish job only when _all_ production jobs have passed, regardless of moving jobs from experimental to prod
  Eg: currently we trigger publish when diego track is green, regardless of upgrade task or eirini track

**Describe alternatives you've considered**

**Additional context**

See:
https://github.com/cloudfoundry-incubator/kubecf/issues/682
https://github.com/cloudfoundry-incubator/kubecf/issues/443
https://github.com/cloudfoundry-incubator/kubecf/issues/665
https://github.com/cloudfoundry-incubator/kubecf/issues/602

**Comment by viccuad** [comment]
closing, moving away from concourse.
