### ISSUE TITLE
 Configurable multi-stack support

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#1086]
# Acceptance Criteria

- [X] Implement proposal and get it merged (done in #1202)
- [ ] Update documentation about bumping buildpacks (and cf-deployment). Should have been part of #1202 but wasn't.
- [X] BLOCKER Update pipelines that bump stemcells and buildpacks to update the new locations
- [ ] Create issue to write tests, both for templating logic and for the validating schema
- [X] Create a proposal for imagePullSecrets support: #1421
- [ ] Create issue to review current configuration options and create guidelines for creating new settings

# Configurable multi-stack support in KubeCF

Currently KubeCF supports 2 builtin stacks, the upstream `cflinuxfs3` stack, and the SUSE `sle15` stack.

Definitions for the stacks are distributed over many files, with additional files required for each buildpack for each stack. This makes adding or replacing a stack tedious work that essentially creates a fork unless the new stack definitions are merged into the core KubeCF sources.

This text tries to prescribe a mechanism to define stacks in a declarative way, so that they can be added to a KubeCF release without requiring changes to the core chart itself at all.

## Goals

* Builtin stacks are built into the charts and not defined by `values.yaml`.

* Builtin stacks can be updated at deployment time with newer root filesystems and buildpacks.

* Buildpacks can be added to and removed from builtin stacks; the install order can be changed.

* Additional stacks can be declared at deployment time without having to modify the helm chart.

## Declaration in `values.yaml`

```yaml
stacks: [mystack, sle15, cflinuxfs3]

stack:
  mystack:
    description: There are many stacks, but this one is mine!
    registry:
      url: registry.example.com:5000/my-org
      username: ~
      password: ~
    rootfs_image: sle15-release:SLE_15_SP1-25.2-7.0.0_374
    # The eirini_rootfs_image is embedded in the bits-release image and cannot be configured.
    buildpack_list: [ruby]
    buildpacks:
      ruby:
        image: suse-ruby-buildpack:SLE_15_SP1-25.2-7.0.0_374.gb8e8e6af
        file: suse-ruby-buildpack/packages/ruby-buildpack-sle15/ruby-buildpack-sle15-v1.8.19.1-1.1-63c0bb58.zip
  sle15:
    buildpack_list: [+, newlang]
    buildpacks:
      newlang:
        ...
```

Only the stacks listed in `stacks` will be configured, and the first stack in that list will be the default stack.

The `stack` key contains the definitions for additional stacks, or updates to the builtin ones.

It is assumed that all images for a single stack will be loaded from the same registry.

The order of installation is defined by the `buildpack_list`. For builtin stacks, the `+` sign can be used to merge with the builtin buildpack list. `[lang1, +, lang2]` will prepend `lang1-buildpack` to the beginning, and append `lang2-buildpack` at the end of the builtin list.

It should be possible to create all required ops-file logic for dynamic stack configuration from these settings using templating logic.

### Eirini rootfs is not configurable

Right now the rootfs for Eirini is pre-loaded inside the `bits` image and cannot be configured at deployment time. Eirini also does not yet have multi-stack support, so only a single stack image will be available.

Extending Eirini with multi-stack support seems to be a larger effort and will probably not be available in the very near future (needs a champion). But if it does materialize then the eirini rootfs image definition can easily be added to the structure above.

### Buildpacks are unrelated to stemcells

The buildpacks should not include a stemcell name in their tags. The stemcell can even be a different OS than the rootfs.

E.g. the `sle15` Ruby buildpack defined above should just be called `suse-ruby-buildpack:1.8.19.1`.

There will be a separate proposal expanding on this.

### Buildpack filenames should be standardized

There is no good reason why the `file` path must be specified explicitly. The CI building the releases should use the upstream naming convention and put the ZIP into: `packages/$LANG-buildpack-$STACK/$LANG-buildpack-$STACK-v$VERSION.zip` based on a buildpack definition like:

```yaml
stack:
  $STACK:
    buildpacks:
      $LANG: my-buildpack:$VERSION
```

The old format will continue to be supported for backwards compatibility.

## Deprecations

The settings for `features.suse_buildpacks` and `features.suse_stack` will go away. The KubeCF helm chart should throw an error if these are still defined, to prevent errors during upgrades.

**Comment by jbuns** [comment]
@jandubois I think that this is a good plan for the future of supporting multiple stacks. It allows for a self-contained way to bring-your-own-stack+buildpacks (BYOSB).

**Comment by jbuns** [comment]
@jandubois just wondering, would the result of this work mean that the kubecf deployment should only have 1 set of buildpacks available when doing a `cf buildpacks`?

**Comment by jimmykarily** [comment]
I'm assuming built-in means all the buildpacks we add in ops files (anything not added by values.yaml). "built-in" may not be a good term to describe these buildpacks because after deployment, all the buildpacks will be "built-in" (as compared to custom buildpacks pushed by the operator after deployment). 

In any case, when using the `+` symbol to merge the built-in buildpacks, are those only the built-in buildpacks for the current stack (we are using it inside a stack block) or is it all the built-in buildpacks? In other words, can I use `+` in two different stacks in their buildpack_list? This is only relevant in case we ship with built-in buildpacks for more than one stack.

**Comment by mook-as** [comment]
👍 this looks a lot cleaner than our current overlapping-ish configuration.

Do we actually need builtin ("bundled" would probably be a better name) buildpacks at all? Since they are presented the same to CF (the buildpack installer tasks &c), can we not just have them listed in the values file (for the user to override) and not in ops files?  This way we wouldn't need the `+` thing either.  That is: why is the first goal there?

I don't really _like_ the duplication in `stacks` / `stack.*` and `buildpack_list` / `buildpacks.*`, but this is a values file and not a thing that we apply ops files to, so the more natural `stacks.[].name` / `buildpacks.[].name` (like instance groups in the BOSH manifest) wouldn't be ergonomic for administrators to modify.  We should at least be consistent on the naming convention though :)

**Comment by jandubois** [comment]
> would the result of this work mean that the kubecf deployment should only have 1 set of buildpacks available when doing a `cf buildpacks`?

It depends. If you install with e.g. `helm install ... --set stacks={cflinuxfs3}`, then you should only have the buildpacks for the `cflinuxfs3` stack. But if you configure multiple stacks, you would have multiple sets of buildpacks.

**Comment by jandubois** [comment]
> I'm assuming built-in means all the buildpacks we add in ops files (anything not added by values.yaml). "built-in" may not be a good term to describe these buildpacks because after deployment, all the buildpacks will be "built-in" (as compared to custom buildpacks pushed by the operator after deployment).

I used "built-in" stacks from the perspective of the helm chart, whereas "custom" stacks would be additional stacks defined by the user during deployment. Would "pre-defined" work better for you?

> In any case, when using the `+` symbol to merge the built-in buildpacks, are those only the built-in buildpacks for the current stack (we are using it inside a stack block) or is it all the built-in buildpacks? In other words, can I use `+` in two different stacks in their buildpack_list? This is only relevant in case we ship with built-in buildpacks for more than one stack.

Each stack has their own `buildpack_list` that defines the order, in which they are declared. The `+` special name will inline the pre-defined list of buildpacks for the same stack name. So yes, you can use it in multiple stacks.

The idea is that stacks are processed in the order specified in `stacks`. All buildpacks for the stack are defined for each stack in the order specified by `buildpacks_list` before moving on to the next stack.

The order of the stacks does not really matter, except for the very first one being the default stack that is used by `cf push` when no `-s` option is used.

For auto-detection the stager will only cycle through the buildpacks for the already selected stack, so the relative order to buildpacks from other stacks doesn't matter.

The order of buildpacks for the same stack matters because the buildpacks can have overlapping detect logic. E.g. the staticfile or nginx buildpacks could lay claim to a PHP app if they get checked before the php buildpack.

**Comment by jandubois** [comment]
> Do we actually need builtin ("bundled" would probably be a better name) buildpacks at all? Since they are presented the same to CF (the buildpack installer tasks &c), can we not just have them listed in the values file (for the user to override) and not in ops files? This way we wouldn't need the `+` thing either. That is: why is the first goal there?

Nobody seems to like the word "builtin". Now "bundled" doesn't sound significantly different to me (and also not quite right). How about "pre-defined"?

I feel quite strongly that at least the buildpack image names and versions should **not** be included in `values.yaml`. Anything that is specific to the current release and will very likely change in the next release should be defined elsewhere. 

`values.yaml` can provide an override mechanism, but not the current values. That way it remains safe to re-use `values.yaml` when updating to a newer version of the chart (assuming that the user used the current `values.yaml` as a template to create a customization file, as some users seem to do).

I can see though that listing the definitions of the pre-defined stacks as part of the `README.md` of the chart could be useful for users wanting to customize it.

> I don't really _like_ the duplication in `stacks` / `stack.*` and `buildpack_list` / `buildpacks.*`, but this is a values file and not a thing that we apply ops files to, so the more natural `stacks.[].name` / `buildpacks.[].name` (like instance groups in the BOSH manifest) wouldn't be ergonomic for administrators to modify. We should at least be consistent on the naming convention though :)

I don't like having 2 settings instead of 1 either, but decided to go with it for user convenience.

As for the names themselves, we can bikeshed what they should be. Should `stacks` become `stack_list`? Or do you have a better suggestion for `buildpacks_list`? I'm not attached to any of these names (nor to the `+` name to reference the builtin list), but couldn't come up with better names yet.

**Comment by mook-as** [comment]
> I feel quite strongly that at least the buildpack image names and versions should not be included in values.yaml. Anything that is specific to the current release and will very likely change in the next release should be defined elsewhere.

Assuming we expect people to grab `values.yaml` out of `helm inspect`, and then reuse it across versions, I can understand then
> Builtin stacks are built into the charts and not defined by values.yaml.

How much logic can we run here? Can we ship the stack + buildpack definition as a YAML file (in the same syntax as `values.yaml`), and read things out of there?  Then we can just point people to it (possibly the definition in the kuberenetes chart repo?) for reference, with comments saying not to copy it? _That_ would definitely require a spike to see if we can bend helm to our will, I think.

> As for the names themselves, we can bikeshed what they should be.

I'm happy with either `stacks` + `buildpacks` or `stack_list` + `buildpack_list`, as long as it's consistent. Flip a coin if that seems easier — I don't really have an opinion there :D

**Comment by jandubois** [comment]
> > Builtin stacks are built into the charts and not defined by values.yaml.
> 
> How much logic can we run here? Can we ship the stack + buildpack definition as a YAML file (in the same syntax as `values.yaml`), and read things out of there? Then we can just point people to it (possibly the definition in the kuberenetes chart repo?) for reference, with comments saying not to copy it? _That_ would definitely require a spike to see if we can bend helm to our will, I think.

As you later found out yourself, there seems to be an undocumented `fromYAML` function in helm that should make this easy.

> > As for the names themselves, we can bikeshed what they should be.
> 
> I'm happy with either `stacks` + `buildpacks` or `stack_list` + `buildpack_list`, as long as it's consistent. Flip a coin if that seems easier — I don't really have an opinion there :D

I think I prefer the `*_list` forms over `*s`. They are a little bit unwieldy, but at least they differ by more than a single character from the other version, making them more separate in my brain.

**Comment by viovanov** [comment]
> # Configurable multi-stack support in KubeCF
> Currently KubeCF supports 2 builtin stacks, the upstream `cflinuxfs3` stack, and the SUSE `sle15` stack.
> 
> Definitions for the stacks are distributed over many files, with additional files required for each buildpack for each stack. This makes adding or replacing a stack tedious work that essentially creates a fork unless the new stack definitions are merged into the core KubeCF sources.

👍

> 
> This text tries to prescribe a mechanism to define stacks in a declarative way, so that they can be added to a KubeCF release without requiring changes to the core chart itself at all.
> 
> ## Goals
> * Builtin stacks are built into the charts and not defined by `values.yaml`.
I don't yet understand what this means. Any component in KubeCF is overrideable from `values.yaml`.
This is a feature that we shouldn't remove. Are you talking about defaults?

> * Builtin stacks can be updated at deployment time with newer root filesystems and buildpacks.
Can you expand on this? Seems to conflict with the first bullet point. How do I use a newer version if I can't use `values.yaml`?

> * Buildpacks can be added to and removed from builtin stacks; the install order can be changed.

👍

> * Additional stacks can be declared at deployment time without having to modify the helm chart.

👍

> 
> ## Declaration in `values.yaml`

Would rename `stack` to `stacks` and `stacks` to `installed_stacks`.

> ```yaml
> stacks: [mystack, sle15, cflinuxfs3]
> 
> stack:
>   mystack:
>     description: There are many stacks, but this one is mine!
>     registry:
>       url: registry.example.com:5000/my-org
>       username: ~
>       password: ~
>     rootfs_image: sle15-release:SLE_15_SP1-25.2-7.0.0_374
>     # The eirini_rootfs_image is embedded in the bits-release image and cannot be configured.
>     buildpack_list: [ruby]
>     buildpacks:
>       ruby:
>         image: suse-ruby-buildpack:SLE_15_SP1-25.2-7.0.0_374.gb8e8e6af
>         file: suse-ruby-buildpack/packages/ruby-buildpack-sle15/ruby-buildpack-sle15-v1.8.19.1-1.1-63c0bb58.zip
>   sle15:
>     buildpack_list: [+, newlang]
>     buildpacks:
>       newlang:
>         ...
> ```
> 
> Only the stacks listed in `stacks` will be configured, and the first stack in that list will be the default stack.
> 
> The `stack` key contains the definitions for additional stacks, or updates to the builtin ones.
> 
> It is assumed that all images for a single stack will be loaded from the same registry.
> 
> The order of installation is defined by the `buildpack_list`. For builtin stacks, the `+` sign can be used to merge with the builtin buildpack list. `[lang1, +, lang2]` will prepend `lang1-buildpack` to the beginning, and append `lang2-buildpack` at the end of the builtin list.

Could we use 2 keys, `append_buildpacks` and `prepend_buildpacks` instead of the special `+`?

> 
> It should be possible to create all required ops-file logic for dynamic stack configuration from these settings using templating logic.

👍

> 
> ## Limitations
> ### Eirini rootfs is not configurable
> Right now the rootfs for Eirini is pre-loaded inside the `bits` image and cannot be configured at deployment time. Eirini also does not yet have multi-stack support, so only a single stack image will be available.
> 
> Extending Eirini with multi-stack support seems to be a larger effort and will probably not be available in the very near future (needs a champion). But if it does materialize then the eirini rootfs image definition can easily be added to the structure above.

I think this is still possible with Eirini, in 2 phases.
For part 1, we could define how the bits image is tagged, so it advertises the stack within.
This would allow us to construct a bits image reference with the correct tag, based on bits version and builtin stack. Ping @jbuns  - wdyt?.
In phase 2, we'd use kpack + paketto, where we should [find native support](https://github.com/pivotal/kpack/pull/256/files).
I couldn't quickly find docs for the Stack CRD, but we should look into it, to make sure this proposal is future proof.

> 
> ### Buildpacks are unrelated to stemcells
> The buildpacks should not include a stemcell name in their tags. The stemcell can even be a different OS than the rootfs.
> 

You mean buildpack images? Since they're built using fissile, it might not make sense to change that right now, since CNCF buildpacks are coming.

> E.g. the `sle15` Ruby buildpack defined above should just be called `suse-ruby-buildpack:1.8.19.1`.
> 
> There will be a separate proposal expanding on this.
> 
> ### Buildpack filenames should be standardized
> There is no good reason why the `file` path must be specified explicitly. The CI building the releases should use the upstream naming convention and put the ZIP into: `packages/$LANG-buildpack-$STACK/$LANG-buildpack-$STACK-v$VERSION.zip` based on a buildpack definition like:
> 
> ```yaml
> stack:
>   $STACK:
>     buildpacks:
>       $LANG: my-buildpack:$VERSION
> ```
> 
> The old format will continue to be supported for backwards compatibility.
> 
> ## Deprecations
> The settings for `features.suse_buildpacks` and `features.suse_stack` will go away. The KubeCF helm chart should throw an error if these are still defined, to prevent errors during upgrades.

We should deprecate for a version as defined by semver.

**Comment by jbuns** [comment]
> Limitations
> Eirini rootfs is not configurable
> Right now the rootfs for Eirini is pre-loaded inside the bits image and cannot be configured at deployment time. Eirini also does not yet have multi-stack support, so only a single stack image will be available.
> 
> Extending Eirini with multi-stack support seems to be a larger effort and will probably not be available in the very near future (needs a champion). But if it does materialize then the eirini rootfs image definition can easily be added to the structure above.
> 
> I think this is still possible with Eirini, in 2 phases.
> For part 1, we could define how the bits image is tagged, so it advertises the stack within.
> This would allow us to construct a bits image reference with the correct tag, based on bits version and builtin stack. Ping

@viovanov we are fine either way since we're already (or at least in the process of) building the bits image with a UBI-based rootfs

**Comment by jandubois** [comment]
@viovanov 

> > * Builtin stacks are built into the charts and not defined by `values.yaml`.
> 
> I don't yet understand what this means. Any component in KubeCF is overrideable from `values.yaml`.
> This is a feature that we shouldn't remove. Are you talking about defaults?

Yes, the default values are going to be stored in a separate YAML file inside the chart and can be read via `fromYAML`. They should be in the same format as the structure in `values.yaml`.

> > * Builtin stacks can be updated at deployment time with newer root filesystems and buildpacks.
> 
> Can you expand on this? Seems to conflict with the first bullet point. How do I use a newer version if I can't use `values.yaml`?

You can still use `values.yaml` to override the settings. There are just no default values in that file.

> Would rename `stack` to `stacks` and `stacks` to `installed_stacks`.

Welcome to "bikeshedders-r-us"! So far the consensus was `stack` and `stack_list`. I'm fine with your suggestion as long as we then also rename `buildpack_list` to `installed_buildpacks`.

> Could we use 2 keys, `append_buildpacks` and `prepend_buildpacks` instead of the special `+`?

Yes, we could. I don't like the special `+` either, but your suggestion lacks the ability to drop any of the builtin buildpacks, so would need a third key to indicate if they are included between prepended and appended buildpacks. So now I don't like turning one setting into three that much either... Better suggestions welcome!

> You mean buildpack images? Since they're built using fissile, it might not make sense to change that right now, since CNCF buildpacks are coming.

Yes, the buildpack images. Note that the proposal includes a mechanism to consume them as-is. The idea was just to simplify this in the future, if we continue to ship buildpack container images. Maybe we will drop this if the switch to kpack is imminent.

> We should deprecate for a version as defined by semver.

I don't know if this is really necessary. We can test if the old values are still being set, and throw a fatal error when you instantiate the template. People will then update their own `config-values.yaml` file (if they did override buildpacks). So you would be prevented from even installing it. I don't see much value in announcing this change in release notes when people cannot do anything about it, as I wouldn't want to support the old and the new config settings in the same release.

Deprecation is useful when you have an old API, and a new API that people can move to while the deprecated API is still working. But if there is a hard switchover, there is no value in a deprecation cycle; you just must ensure that the new version cannot be misconfigured.

**Comment by jandubois** [comment]
> I couldn't quickly find docs for the Stack CRD, but we should look into it, to make sure this proposal is future proof.

For now I want to keep it outside the scope of this proposal, but will do some research as part of #1113

**Comment by jbuns** [comment]
@jandubois just wondering if we have enough to start creating stories around this spike, which we'd be happy to pick up

**Comment by jandubois** [comment]
@jbuns Hi Jeff, I was originally planning to work on a proof-of-concept for this proposal during out internal hack-week, but didn't actually get a chance to participate due to other obligations. I've been working on the templates for this during the current week and hope to have something to show early next week. Sorry, wanted to keep this one for myself, because reasons. 😀

**Comment by jbuns** [comment]
@jandubois no worries and thanks for the update.
