### ISSUE TITLE
Epic: Streamline and publish build process

### ISSUE THREAD

**Issue by thardeck** [cloudfoundry-incubator/kubecf#1357]
Some pipelines like for example some buildpack pipelines and stemcell building run internally. They should be publicly available.

Build failures on OBS often stay unnoticed so monitoring or mail notification should be put in place to not miss any issues.

The SLE parts should be updated from SLE 15 SP1 to SP2.

## Acceptance criteria

- [ ] All product related pipelines are publicly visible
- [ ] No confidential information is visible without login in the pipelines
- [ ] Build failures in any step result in a notification
- [ ] Every SLE part is updated to SLE15 SP2
- [ ] All dependencies are up to date and links point to openSUSE Leap 15.2
- [ ] The Cloud:Platform OBS [subproject](https://build.opensuse.org/project/subprojects/Cloud:Platform) provides only actively used projects and packages

**Comment by fargozhu** [comment]
@thardeck we need to breakdown in multiple independent issues so it can be tackle in different moments and by other team members.
