### ISSUE TITLE
Migration from SCF

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#308]
**Is your feature request related to a problem? Please describe.**
Support migration from SCF clusters.

**Describe the solution you'd like**
As a user of SCF, I'd like to be able to migrate to kubecf without manually porting my applications.

**Describe alternatives you've considered**
Manual migration.

**Additional context**
https://docs.google.com/document/d/1pD8O92QWKYvzViX1pgloQ-px9vFLbJNeiT18Z_TRcNA/edit?usp=sharing

### Tasks

- [ ] Job for migrating databases
- [ ] Job for migrating blobstore
- [ ] Templates for env.* and secrets.*
- [ ] Refactor existing settings so they're compatible
- [ ] Docs
